version: "3.9"
name: "kafka-demo"

services:
    zookeeper:
        image: confluentinc/cp-zookeeper:latest
        container_name: zookeeper
        environment:
            - ZOOKEEPER_SERVER_ID=1
            - ZOOKEEPER_CLIENT_PORT=2181

    kafka:
        image: confluentinc/cp-kafka:latest
        container_name: kafka
        ports:
            - "9092:9092"
        environment:
            - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
            - KAFKA_LISTENERS=PLAINTEXT://0.0.0.0:9092
            - KAFKA_LISTENER_SECURITY_PROTOCOL=PLAINTEXT
            - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
            - KAFKA_NUM_PARTITIONS=3
        depends_on:
            - zookeeper
    kafka1:
        image: confluentinc/cp-kafka:latest
        environment:
            - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka1:9093
            - KAFKA_LISTENERS=PLAINTEXT://0.0.0.0:9093
            - KAFKA_LISTENER_SECURITY_PROTOCOL=PLAINTEXT
            - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
            - KAFKA_NUM_PARTITIONS=3
        ports:
            - "9093:9093"
        depends_on:
            - zookeeper
    kafka2:
        image: confluentinc/cp-kafka:latest
        environment:
            - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka2:9094
            - KAFKA_LISTENERS=PLAINTEXT://0.0.0.0:9094
            - KAFKA_LISTENER_SECURITY_PROTOCOL=PLAINTEXT
            - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
            - KAFKA_NUM_PARTITIONS=3
        ports:
            - "9094:9094"
        depends_on:
            - zookeeper

    akhq:
        # build:
        #   context: .
        image: tchiotludo/akhq
        restart: unless-stopped
        environment:
            AKHQ_CONFIGURATION: |
                akhq:
                  connections:
                    docker-kafka-server:
                      properties:
                        bootstrap.servers: "kafka:9092"
                      schema-registry:
                        url: "http://schema-registry:8085"
                      connect:
                        - name: "connect"
                          url: "http://connect:8083"

        ports:
            - 8080:8080
        depends_on:
            - kafka
    php:
        image: stcer/php:8.2-fpm
        volumes:
            - ./php:/var/www/html
