stages:
  - build

rsync-repo:
    script:
        - sh -x /usr/local/sbin/rsyncGitRepo.sh myali ${CI_PROJECT_NAMESPACE}/${CI_PROJECT_NAME} ${CI_COMMIT_REF_NAME} ${CI_COMMIT_SHA}
    stage: build
    tags:
        - dev
    only:
        - master

