version: '3'

services:
  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD_FILE: /conf/root-password
    volumes:
      - ./data/mysql:/var/lib/mysql
      - ./conf/mysql:/conf
  rmq:
    image: rabbitmq:3.8.0-management
    environment:
      RABBITMQ_DEFAULT_VHOST: my_vhost
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS_FILE: /conf/admin-password
    volumes:
      - ./data/rmq:/var/lib/rabbitmq
      - ./conf/rmq:/conf
    ports:
      - 5672:5672
      - 15672:15672
  redis:
    image: redis:alpine
    volumes:
      - ./data/redis:/data
  php:
    depends_on:
      - db
    image: stcer/php:7.4-fpm
    volumes:
      - ./www:/home/www
    deploy:
      mode: replicated
      replicas: 1
  web:
    depends_on:
      - php
    image: nginx
    volumes:
      - ./conf/nginx:/etc/nginx/conf.d
      - ./www:/home/www
    ports:
      - 8090:80
    command: /bin/bash -c "nginx -g 'daemon off;'"
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - 8091:80
