version: '3'

services:

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
    volumes:
      - /home/dockers/web-php/mysql:/var/lib/mysql
  php:
    image: php:7.0-fpm
    restart: always
    volumes:
      - /home/dockers/web-php/www:/home/www
  web:
    image: nginx
    volumes:
      - /home/dockers/web-php/nginx:/etc/nginx/conf.d
      - /home/dockers/web-php/www:/home/www
    ports:
      - 8090:80
    command: /bin/bash -c "nginx -g 'daemon off;'"

