version: '3'

services:
  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
    volumes:
      - ./data/mysql:/var/lib/mysql
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - 8091:80
  rmq:
    image: rabbitmq:3.8.0-management
    environment:
      RABBITMQ_DEFAULT_VHOST: my_vhost 
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: admin
    volumes:
      - ./data/rmq:/var/lib/rabbitmq
    ports:
      - 5672:5672
      - 15672:15672
  redis:
    image: redis:alpine
    volumes:
      - ./data/redis:/data
    ports:
      - 6379:6379
  php:
    image: php:7.1-fpm
    volumes:
      - ./www:/home/www
    deploy:
      mode: replicated
      replicas: 2
  web:
    image: nginx
    volumes:
      - ./conf/nginx:/etc/nginx/conf.d
      - ./www:/home/www
    ports:
      - 8090:80
    command: /bin/bash -c "nginx -g 'daemon off;'"
  visualizer:
    image: dockersamples/visualizer
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock 
    ports:
      - 8081:8080

