version: '3'

services:
  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
    volumes:
      - ./mysql:/var/lib/mysql
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - 8091:80
  php:
    image: php:7.1-fpm
    volumes:
      - ./www:/home/www
    deploy:
      mode: replicated
      replicas: 2
  web:
    image: nginx
    volumes:
      - ./nginx:/etc/nginx/conf.d
      - ./www:/home/www
    ports:
      - 8090:80
    command: /bin/bash -c "nginx -g 'daemon off;'"

  visualizer:
    image: dockersamples/visualizer
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock 
    ports:
      - 8081:8080

