# 文件名：nginx-php-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webapp
  template:
    metadata:
      labels:
        app: webapp
    spec:
      containers:
        - name: php
          image: stcer/php:8.4-fpm
          ports:
            - containerPort: 9000
          volumeMounts:
            - name: www
              mountPath: /var/www/html
        - name: nginx
          image: nginx:latest
          ports:
            - containerPort: 80
          volumeMounts:
            - name: www
              mountPath: /var/www/html
          # nginx 配置 PHP-FPM 代理
          command: ["/bin/sh","-c"]
          args:
            - |
              echo "server {
                listen 80;
                server_name localhost;
                root /var/www/html;
                index index.php index.html;
                location / {
                  try_files \$uri \$uri/ =404;
                }
                location ~ \.php\$ {
                  include fastcgi_params;
                  fastcgi_pass 127.0.0.1:9000;
                  fastcgi_param SCRIPT_FILENAME \$document_root\$fastcgi_script_name;
                }
              }" > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'
      volumes:
        - name: www
          configMap:
            name: webapp-files
